version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - mariadb
        networks:
            - default
    mariadb:
        image: 'bitnami/mariadb:10.1'
        environment:
        - ALLOW_EMPTY_PASSWORD=yes
        volumes:
        - ./www:/var/www/html/
    phpmyadmin:
        image: bitnami/phpmyadmin:latest
        depends_on:
        - mariadb
        ports:
        - '80:80'
        - '443:443'
        volumes:
        - phpmyadmin_data:/bitnami

volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
